spring.application.name=bolsa-empleo
server.port=8080

spring.datasource.url=jdbc:sqlserver://bolsasever.database.windows.net:1433;database=BolsaTrabajoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=CloudSA01d3b220
spring.datasource.password=bolsa1234!


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=userdatabolsa;AccountKey=yfx4X30GJUcB39nLtVMxYEOW6XnE3vJsZr1X8M+6qZEBdmUufsJ2E/lPyXi8+10HwG+OfgD/8WHE+AStU21C0w==;EndpointSuffix=core.windows.net
azure.storage.container-name=archivos-bolsa

springdoc.api-docs.path=/api-docs-json
springdoc.swagger-ui.path=/api-docs