spring.application.name=bolsa-empleo
server.port=${PORT:8080}

spring.datasource.url=jdbc:sqlserver://bolsasever.database.windows.net:1433;database=BolsaTrabajoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=CloudSA01d3b220
spring.datasource.password=bolsa1234!


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION:}
azure.storage.container-name=archivos-bolsa
app.uploads.base-url=/uploads

springdoc.api-docs.path=/api-docs-json
springdoc.swagger-ui.path=/api-docs

jwt.secret=ZGV2LWJvbHNhLWVtcGxlb3Mtc2VjcmV0LWtleS1mb3Itand0LXRva2VuLXNpZ25pbmc=
jwt.expiration-ms=86400000